### ISSUE TITLE
Add simple validations to the Verra CSV data

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/data-pipelines#2]
Add simple validations prior to outputting the Verra CSV data:
  - check that number of rows is either the same or more - not (significantly) less
  - check if number of columns has changed

There are tools for doing this like Great Expectations https://www.prefect.io/partner/great-expectations/

But for now we can just do simple logic checks

**Comment by biwano** [comment]
Basic checks implemented for now.
