### ISSUE TITLE
Rolling history

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/data-pipelines#3]
We need a mechanism to clean up old CSV dumps, ideally with a defined rolling period like 7 days

The deletion operation should always take place AFTER a new file has been dumped for a given dataset

**Comment by biwano** [comment]
Rolling history implemented. Works as follows:
- Data storage:
  - Fetches data
  - Checks data 
  - Stores the data suffixed with a timestamp
  - Stores the data suffixed with "latest"
- Data deletion
  - the clean_up_old_data_flow checks all files for the lake folder and deletes those older than 7 days. (Maybe I should add a check to never delete files prefixed with latest)

**Comment by 0xAurelius** [comment]
Great, that's a good start, but yeah we should have logic to make sure that it will never delete the only available dataset (latest)
