### ISSUE TITLE
[content enrichment] Import enhanced project description to Sanity

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/data-pipelines#7]
[Discord thread](https://discord.com/channels/841390338324824096/1100855732406059129)

updates to the code for more consistent/quality output and added exponential backoff to handle rate limiting, takes about an hour for a full run but its solid -> https://colab.research.google.com/drive/1nmBL4EbhTW5unHd9bC1xABmkhSsyUfmC?usp=sharing

marcus will add this to the import pipeline

data to be added to this Sanity type: https://carbon-projects.sanity.studio/desk/projectContent
![image](https://github.com/KlimaDAO/data-pipelines/assets/103535195/1deed0a5-d81e-46e8-8569-4f9851ec89cd)

**Comment by 0xAurelius** [comment]
This is done but there is some cleanup work, see Discord thread for details
